Make MMTk a runtime option
mmtk/ruby pull request #14
Opened 2022-07-27 22:59 UTC by chrisseaton

It's still enabled at compile-time, via `USE_MMTK` (`USE_THIRD_PARTY_HEAP` is gone) but you now enable using `--mmtk`, (or `RUBYOPT=--mmtk`, or `--enable=mmtk`, or `MMTK_PLAN=...`...)

2022-07-27 23:02 UTC, chrisseaton commented
After this PR, the pattern you should use is

```c
#if USE_MMTK
    ...
#endif
```

or

```c
#if USE_MMTK
    if (mmtk_enable) {
#endif
        ...
#if USE_MMTK
    }
#endif
```

Note that's if `#if`, not `#ifdef`.

2022-07-27 23:37 UTC, chrisseaton commented
Subsequent work will be to reduce the diff with upstream - I may remove the indentation in conditional blocks to avoid merge conflicts in the future.

2022-07-28 04:26 UTC, wks requested changes
Mostly OK.

We defined `rb_mmtk_enabled_p()`, and probably we should use that in all if statements instead of directly using `mmtk_enable`.

There are also some indentation issues, and some are the results of previous changes.  We can fix them in this PR if convenient.

2022-07-28 04:26 UTC, wks commented on gc.c
> +        if (mmtk_enable) {
Should have one less level of indentation.

2022-07-28 04:26 UTC, wks commented on gc.c
> +        }
These mis-indented lines look like a result from expanding tabstops to spaces last time.

2022-07-28 04:26 UTC, wks commented on gc.c
> +            if (!mmtk_enable) {
We also defined `rb_mmtk_enabled_p()`. Should we use that consistently in all guarding `if` statements?

2022-07-28 05:02 UTC, wks reviewed
We can workaround some compiler warnings.

2022-07-28 05:02 UTC, wks commented on gc.c
> +            int marking_bit;
GCC warns that these variables may be used uninitialised.  We know that they must be initialised if `mmtk_enable` is false, and they are only used when `mmtk_enable` is false.  The compiler is just not smart enough.

2022-07-28 05:02 UTC, wks commented on gc.c
> +            if (!mmtk_enable) {
I managed to workaround this by assigning the result to a local variable.  The compiler seems smart enough to analyse the control flow w.r.t. local variables.

```suggestion
            const bool mmtk_enabled_local = rb_mmtk_enabled_p(); 
            if (!mmtk_enabled_local) {
```

2022-07-28 05:02 UTC, wks commented on gc.c
> +            if (!mmtk_enable) {
See above.
```suggestion
            if (!mmtk_enabled_local) {
```

2022-08-02 13:43 UTC, chrisseaton commented
That's all the warnings cleared, and changes made, ready to go I think.

2022-08-03 03:35 UTC, wks approved these changes

2022-08-03 03:41 UTC, merged