Use 80% of physical memory by default
mmtk/ruby pull request #2
Opened 2022-07-11 14:24 UTC by chrisseaton

Fix towards https://github.com/mmtk/mmtk-ruby/issues/1.

2022-07-13 15:38 UTC, wks requested changes
Sorry for the late reply.

I think this default heap size should work in the long run, but currently it may result in the Ruby process being killed by SIGKILL, due to the fact that our current MarkSweep plan cannot precisely determine its memory usage, and may not trigger GC when the heap is exhausted before allocating as much memory as 80% physical memory.

I think there is a small problem when calculating the heap limit.  See my comment in the code.  Other parts of the PR is OK.  I'll merge it after you confirm and fix the problem.

2022-07-13 15:38 UTC, wks commented on gc.c
> +        return rb_mmtk_available_system_memory() / rb_mmtk_heap_limit_percentage * 100;
I think you mean `rb_mmtk_available_system_memory() * rb_mmtk_heap_limit_percentage / 100`.  Otherwise, if `rb_mmtk_heap_limit_percentage == 80`, the return value will be `rb_mmtk_available_system_memory() / 80 * 100` which is `rb_mmtk_available_system_memory() * 1.25`.

```suggestion
        return rb_mmtk_available_system_memory() * rb_mmtk_heap_limit_percentage / 100;
```

2022-07-13 23:10 UTC, chrisseaton commented on gc.c
> +        return rb_mmtk_available_system_memory() / rb_mmtk_heap_limit_percentage * 100;
I spent ages thinking about this and got it wrong!

But I think it should be `system / 100 * percentage`, as your suggested `system * percentage / 100` could overflow couldn't it? (Currently it's `system / percentage * 100`.)

2022-07-14 03:10 UTC, wks commented on gc.c
> +        return rb_mmtk_available_system_memory() / rb_mmtk_heap_limit_percentage * 100;
Yes if the system has 160 petabyte of physical memory, or 4 megabytes of memory for a 32-bit system.  I think the formula `system / 100 * percentage` you suggested is more reasonable given that it is less likely to have less than 100 bytes of system memory.

2022-07-14 10:55 UTC, merged