Support setting the MMTk plan as a flag
mmtk/ruby pull request #7
Opened 2022-07-14 16:51 UTC by chrisseaton

```
% build/bin/ruby --version
ruby 3.2.0dev (2022-07-14T13:31:38Z plan-flag b32b4a53e1) +MMTk(MarkSweep) [x86_64-linux]

% build/bin/ruby --mmtk-plan=NoGC --version                                                           
ruby 3.2.0dev (2022-07-14T13:31:38Z plan-flag b32b4a53e1) +MMTk(NoGC) [x86_64-linux]

% RUBYOPT=--mmtk-plan=NoGC build/bin/ruby --version
ruby 3.2.0dev (2022-07-14T13:31:38Z plan-flag b32b4a53e1) +MMTk(NoGC) [x86_64-linux]

% MMTK_PLAN=NoGC build/bin/ruby --version
ruby 3.2.0dev (2022-07-14T13:31:38Z plan-flag b32b4a53e1) +MMTk(NoGC) [x86_64-linux]
```

Works by setting `MMTK_PLAN` within the process. Complicated, because Ruby argument handling happens after the GC has been initialised, so we do an initial pass to find the values, then just confirm during normal argument parsing.

2022-07-14 16:52 UTC, chrisseaton commented
Work towards https://github.com/mmtk/mmtk-ruby/issues/1.

2022-07-18 11:42 UTC, wks requested changes

2022-07-18 11:42 UTC, wks commented on gc.c
> +    char *env_args = getenv("RUBYOPT");
If `--disable-rubyopt` exists in argv, the `ruby` executable should disregard the `RUBYOPT` environment variable.  We can check for the presence of `--disable-rubyopt` and `--enable-rubyopt` during the previous loop over `argv`.

2022-07-18 11:42 UTC, wks commented on mmtk.h
> +
The header `mmtk.h` is intended to declare things that are defined in Rust.  But these functions are defined in `gc.c`.  Ideally, they should be declared in `gc.h`.  If possible, we should move these declarations to `gc.h`, unless there are technical difficulties (such as cyclic `include`s) that prevent us from doing so.

2022-07-20 02:31 UTC, wks approved these changes
LGTM.

2022-07-20 05:11 UTC, merged